// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package handler

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson888c126aDecodeGithubComKost0L4InternalHandler(in *jlexer.Lexer, out *RequestPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "numbers":
			if in.IsNull() {
				in.Skip()
				out.Numbers = nil
			} else {
				in.Delim('[')
				if out.Numbers == nil {
					if !in.IsDelim(']') {
						out.Numbers = make([]int, 0, 8)
					} else {
						out.Numbers = []int{}
					}
				} else {
					out.Numbers = (out.Numbers)[:0]
				}
				for !in.IsDelim(']') {
					var v1 int
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = int(in.Int())
					}
					out.Numbers = append(out.Numbers, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson888c126aEncodeGithubComKost0L4InternalHandler(out *jwriter.Writer, in RequestPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"numbers\":"
		out.RawString(prefix[1:])
		if in.Numbers == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Numbers {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.Int(int(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson888c126aEncodeGithubComKost0L4InternalHandler(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson888c126aEncodeGithubComKost0L4InternalHandler(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson888c126aDecodeGithubComKost0L4InternalHandler(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson888c126aDecodeGithubComKost0L4InternalHandler(l, v)
}
